import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);
const TEMPLATES_DIR = path.join(process.cwd(), 'email-templates');
const OUTPUT_DIR = path.join(process.cwd(), 'lib/email/templates');
const TYPES_FILE = path.join(process.cwd(), 'lib/email/types.ts');

interface TemplateFile {
  name: string;
  category: string;
  fullPath: string;
}

// Find all .mjml files
function findTemplates(dir: string, category: string = ''): TemplateFile[] {
  const files: TemplateFile[] = [];
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      // Skip layouts directory
      if (item !== 'layouts') {
        files.push(...findTemplates(fullPath, item));
      }
    } else if (item.endsWith('.mjml')) {
      files.push({
        name: item.replace('.mjml', ''),
        category,
        fullPath,
      });
    }
  }

  return files;
}

// Compile MJML to HTML
async function compileTemplate(inputPath: string, outputPath: string): Promise<void> {
  const { stdout, stderr } = await execAsync(
    `npx mjml "${inputPath}" -o "${outputPath}"`
  );

  if (stderr && !stderr.includes('compiled successfully')) {
    console.error(`Error compiling ${inputPath}:`, stderr);
  }
}

// Generate TypeScript types
function generateTypes(templateNames: string[]): string {
  const names = templateNames.map((n) => `  | '${n}'`).join('\n');

  return `// Auto-generated by lib/email/compiler.ts
// Do not edit manually

export type EmailTemplate =
${names};

export interface SendOptions {
  to: string | string[];
  subject: string;
  data: Record<string, string | number | boolean | undefined>;
  from?: string;
  replyTo?: string;
}

export interface SendResult {
  success: boolean;
  error?: string;
  messageId?: string;
}
`;
}

// Main compilation function
async function compile(): Promise<void> {
  console.log('🔨 Compiling MJML templates...');

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Find all templates
  const templates = findTemplates(TEMPLATES_DIR);

  if (templates.length === 0) {
    console.log('No templates found');
    return;
  }

  console.log(`Found ${templates.length} template(s)`);

  // Compile each template
  const templateNames: string[] = [];
  for (const template of templates) {
    const outputPath = path.join(OUTPUT_DIR, `${template.name}.html`);
    await compileTemplate(template.fullPath, outputPath);
    templateNames.push(template.name);
    console.log(`  ✓ ${template.name}`);
  }

  // Generate types file
  fs.writeFileSync(TYPES_FILE, generateTypes(templateNames));
  console.log(`\n✅ Generated ${TYPES_FILE}`);

  console.log(`\n✅ Compiled ${templateNames.length} template(s)`);
}

// Watch mode
async function watch(): Promise<void> {
  console.log('👀 Watching MJML templates for changes...');

  let isRunning = false;
  const debounce = () => {
    if (isRunning) return;
    isRunning = true;

    compile().then(() => {
      isRunning = false;
    });
  };

  // Simple polling for watch mode
  setInterval(() => {
    const templates = findTemplates(TEMPLATES_DIR);
    for (const template of templates) {
      const outputPath = path.join(OUTPUT_DIR, `${template.name}.html`);
      if (!fs.existsSync(outputPath)) {
        debounce();
        break;
      }
      const inputMtime = fs.statSync(template.fullPath).mtime;
      const outputMtime = fs.statSync(outputPath).mtime;
      if (inputMtime > outputMtime) {
        debounce();
        break;
      }
    }
  }, 1000);

  // Initial compile
  await compile();
}

// CLI
const args = process.argv.slice(2);
const watchMode = args.includes('--watch');

if (watchMode) {
  watch();
} else {
  compile();
}
