// Auto-generated by lib/email/compiler.ts
// Do not edit manually

export type EmailTemplate =
  | 'email-verification'
  | 'magic-link'
  | 'password-reset'
  | 'account-verified'
  | 'welcome';

export interface SendOptions {
  to: string | string[];
  subject: string;
  data: Record<string, string | number | boolean | undefined>;
  from?: string;
  replyTo?: string;
}

export interface SendResult {
  success: boolean;
  error?: string;
  messageId?: string;
}
